name = "parchment"
description = "Parchment theme, by jasonfry.co.uk"
license = "MIT"
homepage = "https://github.com/jsonfry/parchment"
min_version = "0.23.4"
demo = "https://whispers-on-parchment.jasonfry.co.uk"

[author]
name = "Jason Fry"
homepage = "https://jasonfry.co.uk"
